services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
      - app_cache:/workspace/__pycache__
    working_dir: /workspace
    command: python main.py
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true

volumes:
  app_cache: 